apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Values.image.name }}-{{ .Chart.AppVersion }}-{{ .Values.image.tag }}
    version: "{{ .Chart.AppVersion }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:  
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "fullname" . }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }} # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name | quote }}
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: DB_NAME
        - name: DB_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: DB_SERVICE_NAME