# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: ashish932/parse-server
  pullPolicy: IfNotPresent
## Image Tag useful when externalDB is been used
  tag: latest
service:
  portName: node
  type: ClusterIP
  externalPort: 80
  internalPort: 1337
resources:
  limits:
    cpu: 350m
    memory: 1000Mi
  requests:
    cpu: 150m
    memory: 250Mi

## Read about PostDistribution budget at https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
## Use only on a clustered setup
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1

##
## MySql chart configuration
##
## https://github.com/helm/charts/tree/master/stable/mysql
##
mongodb:
  mongodbUsername: parse
  mongodbDatabase: test
  usePassword: false
  replicaSet:
    enabled: true
  imageTag: 5.7


##
## For custom mysql and postgres database. Use externalDB. 
## Would be used only if postgres and mysql is disabled.
## Set the image tag if want to use externalDB
##
db:
  user: parse
  serviceName: parse
  name: parse
  password: parse

ingress:
  enabled: true
  issuer: dev-issuer
  annotations:
    kubernetes.io/ingress.class: nginx
storage: "1Gi"
storageClassName: "my-storage-class"
buildID: "123"



## Prometheus Exporter / Metrics
##
metrics:
  enabled: true

    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName

  ## String with extra arguments to the metrics exporter
  ## ref: https://github.com/dcu/mongodb_exporter/blob/master/mongodb_exporter.go
  extraArgs: ""
  ## Metrics exporter pod Annotation
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "1337"

  ## Prometheus Service Monitor
  ## ref: https://github.com/coreos/prometheus-operator
  ##      https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md
  serviceMonitor:
    ## If the operator is installed in your cluster, set to true to create a Service Monitor Entry
    enabled: false

    ## Specify a namespace if needed
    # namespace: monitoring

    ## Used to pass Labels that are used by the Prometheus installed in your cluster to select Service Monitors to work with
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
    additionalLabels: {}

    ## Specify Metric Relabellings to add to the scrape endpoint
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
    # relabellings:

    alerting:
      ## Define individual alerting rules as required
      ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#rulegroup
      ##      https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
      rules: {}

      ## Used to pass Labels that are used by the Prometheus installed in your cluster to select Prometheus Rules to work with
      ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
      additionalLabels: {}
